---
json_rpc_url: https://api.mainnet-beta.solana.com
websocket_url: ''
keypair_path: /root/.config/solana/futurus.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: confirmed
